/* Krąg — mapowanie nazwy źródła (f.s) na URL strony źródłowej.
 * Wyłącznie realne adresy z kuratorskiego sources.json (Warstwa 4). Źródła bez URL
 * (czasopisma, „różne organizacje") zostają zwykłym tekstem — nie zmyślamy linków.
 */
export const SRC_URL = {
  "Krajowe Centrum ds. AIDS / gov.pl": "https://www.hiv-aids.edu.pl/",
  "Polskie Towarzystwo Naukowe AIDS": "https://ptnaids.pl/wp-content/uploads/2025/06/Rekomendacje_PTN_AIDS_2025_2.pdf",
  "Krajowe Centrum ds. AIDS": "https://www.hiv-aids.edu.pl/",
  "Centers for Disease Control and Prevention (US)": "https://www.cdc.gov/hiv/",
  "Patel P. i in., AIDS 2014;28(10):1509–1519": "https://www.ashasexualhealth.org/pdfs/cdc-hiv-risk-behaviors.pdf",
  "European AIDS Clinical Society": "https://eacs.sanfordguide.com/",
  "NIZP-PZH": "https://wwwold.pzh.gov.pl/oldpage/epimeld/hiv_aids/2024.htm",
  "University of Washington / HRSA": "https://www.hiv.uw.edu/",
  "HIV i-Base": "https://i-base.info/",
  "NAM Publications": "https://www.aidsmap.com/",
  "Prevention Access Campaign": "https://preventionaccess.org/",
  "NYSDOH AIDS Institute Clinical Guidelines Program": "https://www.hivguidelines.org/guideline/u-equals-u/",
  "NIH / DHHS (US)": "https://clinicalinfo.hiv.gov/",
  "The Well Project": "https://www.thewellproject.org/hiv-information/can-i-breastfeed-while-living-hiv",
  "amfAR": "https://www.amfar.org/",
  "International AIDS Society": "https://www.iasociety.org/",
  "UCSF": "https://prep.ucsf.edu/",
  "Molina J-M. i in., NEJM 2015": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7174437/",
  "Gilead Sciences / FDA": "https://www.gilead.com/",
  "New England Journal of Medicine": "https://www.nejm.org/",
  "World Health Organization": "https://www.who.int/health-topics/hiv-aids",
  "Rynek Zdrowia (prasa branżowa)": "https://www.rynekzdrowia.pl/",
  "GdziePoLek.pl": "https://www.gdziepolek.pl/",
  "Zjednoczenie Pozytywni w Tęczy": "https://pozytywniwteczy.pl/",
  "gov.pl": "https://www.gov.pl/web/aids",
  "Stowarzyszenie „Jeden Świat\"": "https://jedenswiat.org.pl/",
  "PKD Poznań": "https://pkdpoznan.pl/pep-poznan-gdzie-zglosic",
  "Ustawodawca RP": "https://isap.sejm.gov.pl/",
  "Termedia (prasa branżowa)": "https://www.termedia.pl/",
  "UNAIDS": "https://www.unaids.org/",
  "Parlament Europejski i Rada UE": "https://eur-lex.europa.eu/legal-content/PL/TXT/?uri=CELEX%3A32016R0679",
  "International Labour Organization": "https://www.ilo.org/",
  "Ministerstwo Zdrowia": "https://www.gov.pl/web/zdrowie",
  "Narodowy Fundusz Zdrowia": "https://www.nfz.gov.pl/",
  "Fundacja Edukacji Społecznej": "https://www.fes.edu.pl/zyjezhiv",
  "naTemat.pl": "https://natemat.pl/",
  "DHHS": "https://clinicalinfo.hiv.gov/",
  "NAM": "https://www.aidsmap.com/"
};
export function srcUrl(name) { return SRC_URL[name] || null; }
